### ISSUE TITLE
AttributeError: 'CNF' object has no attribute '_compress_clause'

### ISSUE THREAD

**Issue by wotaoyanh** [LUMII-Syslab/QuerySAT#2]
Hi, i cannot find '_compress_clause' in class CNF, please help!

Initializing new model!
Converting DIMACS data from 'host-dir/data/SAT_3/dimacs/validation_5_100' into 'host-dir/data/SAT_3/tf_records/validation_20000_5_100'!
Created 0 data batches in host-dir/data/SAT_3/tf_records/validation_20000_5_100...

Generating DIMACS data in 'host-dir/data/SAT_3/dimacs/train_5_100' directory!
Traceback (most recent call last):
  File "main.py", line 265, in <module>
    main()
  File "main.py", line 32, in main
    train(dataset, model, ckpt, manager)
  File "main.py", line 175, in train
    train_data = dataset.train_data()
  File "/home/ubuntu2004/work/QuerySAT-master/data/dimac.py", line 59, in train_data
    data = self.fetch_dataset(self.train_generator, mode="train")
  File "/home/ubuntu2004/work/QuerySAT-master/data/dimac.py", line 85, in fetch_dataset
    self.write_dimacs_to_file(dimacs_folder, generator)
  File "/home/ubuntu2004/work/QuerySAT-master/data/dimac.py", line 110, in write_dimacs_to_file
    for idx, (n_vars, clauses, *solution) in enumerate(data_generator()):
  File "/home/ubuntu2004/work/QuerySAT-master/data/CNFGen.py", line 41, in _generator
    iclauses = [F._compress_clause(x) for x in clauses]
  File "/home/ubuntu2004/work/QuerySAT-master/data/CNFGen.py", line 41, in <listcomp>
    iclauses = [F._compress_clause(x) for x in clauses]
AttributeError: 'CNF' object has no attribute '_compress_clause'

**Comment by EmilsOzolins** [comment]
Hi, I am sorry that you had issues running our project.

We had misconfigured the requirements file, causing the installation of `cfngen==0.9.1` instead of `cfngen==0.9.0`. The project requires exactly `cnfgen==0.9.0`, and the script should work fine if you reinstall it by running `pip install cnfgen==0.9.0`.
We have also pushed changes to represent these nuances correctly in requerements.txt file.

**Comment by wotaoyanh** [comment]
> Hi, I am sorry that you had issues running our project.
> 
> We had misconfigured the requirements file, causing the installation of `cfngen==0.9.1` instead of `cfngen==0.9.0`. The project requires exactly `cnfgen==0.9.0`, and the script should work fine if you reinstall it by running `pip install cnfgen==0.9.0`. We have also pushed changes to represent these nuances correctly in requerements.txt file.

nice work! thank you! ^ ^
